# Generated by Django 3.2.3 on 2021-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_created=True)),
                ('word', models.TextField()),
                ('translation', models.TextField()),
                ('is_learned', models.BooleanField(default=False)),
            ],
        ),
    ]
