# Generated by Django 3.2.3 on 2021-05-16 17:44
import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'verbose_name': 'Flash card', 'verbose_name_plural': 'Flash cards'},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_revised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='translation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table='flash_cards',
        ),
        migrations.CreateModel(
            name='CardsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crated_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('is_verbose', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card group',
                'verbose_name_plural': 'Card groups',
                'db_table': 'card_groups',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='cards_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flash_card', to='flash_cards.cardsgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcard',
            unique_together={('cards_group', 'word')},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='creation_time',
        ),
    ]
